[profile.default]
auto_detect_solc = false
evm_version = "shanghai"
ffi = true
fuzz = { runs = 1_000 }
gas_reports = ["*"]
optimizer = true
optimizer_runs = 10_000
out = "out"
script = "script"
solc = "0.8.28"
src = "src"
test = "tests"
lib = "node_modules"
libs = ["lib"]
remappings = [
    "prb-math/=node_modules/@prb/math/src/",
    "forge-std/=node_modules/forge-std/src/",
    "@src/=src/",
    "@test/=tests/"
]

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4

[etherscan]
mainnet = { key = "${API_KEY_ETHERSCAN}" }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

